config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
  resources :users, only: [:edit, :show, :update]
  resources :gameweeks, only: [:index, :show]
  resources :fixtures, only: [:index, :create]
  get 'standings', to: 'standings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixture.rb
class Fixture < ApplicationRecord
  belongs_to :gameweek
end

app/models/gameweek.rb
class Gameweek < ApplicationRecord
  has_many :fixtures, dependent: :destroy
  has_many :results, dependent: :destroy
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :gameweek
end

app/models/user.rb
class User < ApplicationRecord
  include UserConcern

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :results, dependent: :destroy

  STANDINGS_COLUMNS = %w[id team name points current_streak current_pick].freeze

  scope :standings, lambda {
    standings_query(STANDINGS_COLUMNS)
  }

  scope :standings_without_current_pick, lambda {
    standings_query(STANDINGS_COLUMNS - ['current_pick'])
  }

  scope :get_rank, lambda { |user|
    user_id = user.id
    # Could write a more verbose query to reduce filtering in memory
    # but unconcerned for now due to on the order of 50 users
    standings.select { |u| u.id == user_id }&.first&.rank
  }

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.find_by(email: data['email']) ||
           User.create(
             name: data['name'],
             email: data['email'],
             password: Devise.friendly_token[0, 20]
           )
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path, notice: 'You must log in to view this page.'
    end
  end
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  def index
    gameweek = Gameweek.last
    @week = gameweek.week
    matches = FixturesService.fetch_fixtures(@week)
    FixturesService.save_fixture_if_updated!(matches)
    @are_all_matches_finished = FixturesService.all_finished?(matches)
    FixturesService.score_all_picks_and_increment_gameweek!(matches: matches, gameweek: gameweek) if @are_all_matches_finished
    @fixture = Fixture.find_by(gameweek: gameweek)
    @current_pick = current_user&.current_pick
  end

  def create
    matches = FixturesService.fetch_fixtures(Gameweek.last.week)
    pick = params.permit(:current_pick).fetch(:current_pick)
    @user = current_user
    return head(:forbidden) if @user.current_pick.present? || FixturesService.any_started?(matches)

    if pick.present? && @user.update(current_pick: pick)
      redirect_to fixtures_path
    else
      render 'index'
    end
  end
end

app/controllers/gameweeks_controller.rb
class GameweeksController < ApplicationController
  def index
    @gameweeks = Gameweek.all.order(week: :desc)
  end

  def show
    @gameweek = Gameweek.find(params[:id])
    @fixture = Fixture.find_by(gameweek: @gameweek)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    @rank = user_signed_in? ? User.get_rank(current_user) : nil
  end
end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController
  def index
    @ranked_users = current_user&.current_pick? ? User.standings : User.standings_without_current_pick
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :correct_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def show
    @user = User.includes(results: :gameweek).find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :team)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/gameweeks_helper.rb
module GameweeksHelper
end

app/helpers/standings_helper.rb
module StandingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fixtures/_fixture_button.html.erb
<%= f.radio_button :current_pick, team, id: "current_pick_#{team.parameterize.underscore}", checked: current_pick == team, disabled: current_pick.present? && current_pick != team, required: true %>
<% if current_pick.present?  %>
  <%= f.label "current_pick_#{team.parameterize.underscore}".to_sym, team, class: "#{current_pick == team ? 'locked' : ''}" %>
<% else %>
  <%= f.label "current_pick_#{team.parameterize.underscore}".to_sym, team, class: 'pickable' %>
<% end %>

app/views/fixtures/index.html.erb
<h4>Fixtures</h4>
<h5>Gameweek: <%= @week %></h5>
<%= form_with local: true do |f| %>
  <table class="fixtures">
    <thead>
      <th>
	Home
      </th>
      <th>
      </th>
      <th>
	Away
      </th>
    </thead>
    <tbody>
      <% @fixture&.matches.each do |match| %>
	<tr>
	  <td>
	    <%= render partial: "fixture_button", locals: {team: match['home_team']['name'], f: f, current_pick: @current_pick}%>
	  </td>
	  <td>
	    vs
	  </td>
	  <td>
	    <%= render partial: "fixture_button", locals: {team: match['away_team']['name'], f: f, current_pick: @current_pick}%>
	  </td>
	</tr>
      <% end %>
    </tbody>
  </table>
  <% if user_signed_in? %>
    <div class="mdl-grid">
      <div class="mdl-cell mdl-cell--2-col"></div>
      <div class="mdl-cell mdl-cell--8-col">
	<%= f.submit "Lock Pick", disabled: @current_pick.present? || FixturesService.any_started?(@fixture&.matches), class: "mdl-button mdl-js-button mdl-button--raised mdl-button--full-width mdl-js-ripple-effect" %>
      </div>
    </div>
  <% end %>
<% end %>
<p>Last Updated: <%= @fixture&.updated_at %></p>

app/views/gameweeks/_match_team.html.erb
<div class="match__team mdl-grid">
  <div class="match__team-side mdl-cell mdl-cell--2-col"><%= team_key.humanize.titlecase %></div>
  <div class="match__team-name mdl-cell mdl-cell--4-col"><%= match[team_key]['name'] %></div>
  <div class="match__team-score mdl-cell mdl-cell--2-col">
   <%= match['score']['full_time'][team_key]%>
  </div>
</div>

app/views/gameweeks/index.html.erb
<div class="gameweeks">
  <h4>Gameweeks</h4>
  <ul>
    <% @gameweeks.each do |gameweek| %>
      <li><%= link_to gameweek.week, gameweek %></li>
    <% end %>
  </ul>
</div>

app/views/gameweeks/show.html.erb
<h4>Gameweek: <%= @gameweek.week %></h4>
<div class="gameweek">
  <% @fixture.matches.each do |match| %>
    <div class="match mdl-grid">
      <div class="mdl-cell mdl-cell--1-col"></div>
      <div class="match__time mdl-cell mdl-cell--middle mdl-cell--1-col">
	<div class="match__date">
	  <%= match['utc_date'].to_date %>
	</div>
	<div class="match__status">
	  <%= match['status'] %>
	</div>
      </div>
      <div class="mdl-cell mdl-cell--1-col"></div>
      <div class="match__teams mdl-cell mdl-cell--5-col">
	<%= render partial: 'match_team', locals: {match: match, team_key: 'home_team'}%>
	<%= render partial: 'match_team', locals: {match: match, team_key: 'away_team'}%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Threadstreaks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <%= render "shared/header"%>
      <main class="mdl-layout__content">
	<%= yield %>
      </main>
      <div class="mdl-snackbar mdl-js-snackbar">
	<div class="mdl-snackbar__text">
	</div>
	<button class="mdl-snackbar__action" type="button"></button>
      </div>
      <%= render "shared/footer"%>
    </div>
  </body>
  <script>
   var notification = document.querySelector(".mdl-js-snackbar");
   notification.addEventListener("mdl-componentupgraded", () => {

     var messages = ["<%= notice %>", "<%= alert %>"].filter((s) => (s != ""));
     var data = (message) => ({
       message,
       timeout: 5000
     });
     messages.map((message) => {
       notification.MaterialSnackbar.showSnackbar(data(message));
     });
   });
  </script>
</html>

app/views/pages/main.html.erb
<% if user_signed_in? %>
  <%= render 'shared/dashboard'%>
<% else  %>
  <div class="wrapper__sign-in">
    <%= button_to(user_google_oauth2_omniauth_authorize_path, class: 'mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect button__sign-in') do %>
      <span><%= render 'shared/google_icon' %>Sign in with Google</span>
    <% end %>
  </div>
<% end %>

app/views/shared/_dashboard.html.erb
<div class="dashboard__team-info">
  <%= render 'shared/dashboard/pick' %>
  <%= render 'shared/dashboard/team' %>
  <%= render 'shared/dashboard/rank' %>
</div>
<section class="dashboard__links">
  <div class="dashboard__quarter"></div>
  <div class="dashboard__links--container">
    <%= link_to 'fixtures', fixtures_path, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
    <%= link_to 'standings', standings_path, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
    <%= link_to 'update account', edit_user_path(current_user), method: :get, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
    <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
  </div>
  <div class="dashboard__quarter"></div>
</section>

app/views/shared/_footer.html.erb
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__middle-section">
    <a href="https://soundcloud.com/user-70053674">
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect">
	<div class="mdl-logo">Podcast</div>
      </button>
    </a>
    <a href="https://twitter.com/soccerthread">
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect">
	<div class="mdl-logo">Twitter</div>
      </button>
    </a>
    <a href="https://www.facebook.com/soccerthread/">
      <button class="mdl-button mdl-js-button mdl-js-ripple-effect">
	<div class="mdl-logo">Facebook</div>
      </button>
    </a>
  </div>
</footer>

app/views/shared/_google_icon.html.erb
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 48 48" class="abcRioButtonSvg">
  <g>
    <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
    <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
    <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
    <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
    <path fill="none" d="M0 0h48v48H0z"></path>
  </g>
</svg>

app/views/shared/_header.html.erb
<header class="mdl-layout__header">
  <div class="mdl-layout-icon"></div>
  <div class="mdl-layout__header-row">
    <span class="mdl-layout__title"><%= link_to 'threadstreaks', root_url %></span>
    <div class="mdl-layout-spacer"></div>
    <nav class="mdl-navigation mdl-navigation--only-tablet-or-larger">
      <%= render 'shared/nav_links' %>
    </nav>
  </div>
</header>
<div class="mdl-layout__drawer">
  <nav class="mdl-navigation">
    <%= render 'shared/nav_links' %>
  </nav>
</div>

app/views/shared/_nav_links.html.erb
<%= link_to 'Fixtures', fixtures_path, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
<%= link_to 'Standings', standings_path, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
<%= link_to 'Gameweeks', gameweeks_path, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
<% end %>

app/views/shared/dashboard/_pick.html.erb
<div class="dashboard__pick">
  <% if current_user.current_pick.present? %>
    <div class="dashboard__pick__picked-team">
      <%= current_user.current_pick %>
    </div>
    <span class="mdl-chip">
      <span class="mdl-chip__text">
	LOCKED
      </span>
    </span>
  <% end %>
</div>

app/views/shared/dashboard/_rank.html.erb
<div class="dashboard__rank">
  <%= @rank.ordinalize %> place
</div>

app/views/shared/dashboard/_team.html.erb
<div class="dashboard__team">
  <h3><%= current_user.name %></h3>
  <h2><%= current_user.team %></h2>
</div>

app/views/shared/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul class="mdl-list">
      <% @user.errors.full_messages.each do |msg| %>
	<li class="mdl-list__item">
	  <span class="mdl-list__item-text-body">
	    <%= msg %>
	  </span>
	</li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/standings/index.html.erb
<div class="standings">
  <h4>Standings</h4>
  <table>
    <thead>
      <tr>
	<th></th>
	<th>
	  Team
	</th>
	<th>
	  User
	</th>
	<th>
	  Points
	</th>
	<th>
	  Streak of
	</th>
	<th>
	  Current Pick
	</th>
      </tr>
    </thead>
    <tbody>
      <% @ranked_users.each do |user| %>
	<tr class="zebra">
	  <td>
	    <%= user.rank %>
	  </td>
	  <td>
	    <%= link_to user.team, user_path(user) %>
	  </td>
	  <td>
	    <%= user.name %>
	  </td>
	  <td>
	    <%= user.points %>
	  </td>
	  <td>
	    <%= user.current_streak %>
	  </td>
	  <td>
	    <%= user.try(:current_pick) %>
	  </td>
	</tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class="edit-user">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/users/error_messages' %>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_field :name, class: 'mdl-textfield__input '%>
      <%= f.label :name, class: 'mdl-textfield__label' %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_field :email, class: 'mdl-textfield__input', disabled: true %>
      <%= f.label :email, class: 'mdl-textfield__label' %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= f.text_field :team, class: 'mdl-textfield__input '%>
      <%= f.label :team, class: 'mdl-textfield__label' %>
    </div>

    <%= f.submit 'Save changes', class: 'mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised' %>
  <% end  %>
</div>

app/views/users/show.html.erb
<div class="team">
  <h4><%= @user.team %></h4>
  <table>
    <thead>
      <tr>
	<th>
	  Dates
	</th>
	<th>
	  Week
	</th>
	<th>
	  Team
	</th>
	<th>
	  Points
	</th>
      </tr>
    </thead>
    <tbody>
      <% @user.results.each do |result| %>
	<tr class="zebra">
	  <td>
	    <%= result.date %>
	  </td>
	  <td>
	    <%= result.gameweek.week %>
	  </td>
	  <td>
	    <%= result.pick %>
	  </td>
	  <td>
	    <%= result.points %>
	  </td>
	</tr>
      <% end %>
    </tbody>
  </table>
</div>